<?php
namespace AW\WSS;

if (!defined('ABSPATH')) {
    exit;
}

if (!class_exists('AW\WSS\Settings')) {
    /*
     * Plugin Settings for WooCommerce Soundscan
     *
     * NOTE: The setting names MUST match the variable members (i.e. FTP_HOST = $ftpHost)
     */
    class Settings extends \WC_Integration
    {
        /**
         * Option Name for Settings in DB (Generated by WC)
         * @var string
         */
        const NAME = 'woocommerce_wc-soundscan-settings_settings';

        /**
         * Option Name for FTP Host
         * @var string
         */
        const FTP_HOST = 'ftpHost';

        /**
         * Option Name for Chain No
         * @var string
         */
        const CHAIN_NO = 'chainNo';

        /**
         * Option Name for Login Username for Physical Sales
         * @var string
         */
        const LOGIN_PHYSICAL_NAME = 'physicalName';

        /**
         * Option Name for Login Username for Digital Sales
         * @var string
         */
        const LOGIN_DIGITAL_NAME = 'digitalName';

        /**
         * Option Name for Login Password for Physical Sales
         * @var string
         */
        const LOGIN_PHYSICAL_PWD = 'physicalPwd';

        /**
         * Option Name for Login Password for Digital Sales
         * @var string
         */
        const LOGIN_DIGITAL_PWD = 'digitalPwd';

        /**
         * Option Name for Physical Account No
         * @var string
         */
        const ACCOUNT_NO_PHYSICAL = 'physicalAccount';

        /**
         * Option Name for Digital Account No
         * @var string
         */
        const ACCOUNT_NO_DIGITAL = 'digitalAccount';

        /**
         * Option Name for WooCommerce Category for Music Singles and Albums
         * @var string
         */
        const MUSIC_CATEGORY = 'wcCategory';

        /**
         * Option Name for WooCommerce SubCategory for Albums
         * @var string
         */
        const ALBUM_CATEGORY = 'albumCategory';

        /**
         * Option Name for WooCommerce SubCategory for Tracks (Singles)
         * @var string
         */
        const TRACK_CATEGORY = 'trackCategory';

        /**
         * Option Name for WooCommerce Attribute for Product ISRC
         * @var string
         */
        const ISRC_ATTRIBUTE = 'isrcAttribute';

        /**
         * Option Name for WooCommerce Attribute for Product UPC
         * @var string
         */
        const UPC_ATTRIBUTE = 'upcAttribute';

        /**
         * Option Name for WooCommerce Attribute for Product EAN
         * @var string
         */
        const EAN_ATTRIBUTE = 'eanAttribute';

        /**
         * Option Name for Minimum Digital Track Price
         * @var string
         */
        const DIGITAL_TRACK_MIN_PRICE = 'digitalTrackMinPrice';

        /**
         * Option Name for Minimum Physical Track Price
         * @var string
         */
        const PHYSICAL_TRACK_MIN_PRICE = 'physicalTrackMinPrice';

        /**
         * Option Name for Minimum Digital Album Price
         * @var string
         */
        const DIGITAL_ALBUM_MIN_PRICE = 'digitalAlbumMinPrice';

        /**
         * Option Name for Minimum Physical Album Price
         * @var string
         */
        const PHYSICAL_ALBUM_MIN_PRICE = 'physicalAlbumMinPrice';

        /**
         * Nielsen Soundscan FTP Host Address
         * @var string
         */
        private $ftpHost = '';

        /**
         * Nielsen Soundscan Chain No
         * @var string
         */
        private $chainNo = '';

        /**
         * Nielsen Soundscan Physical Sales Login Username
         * @var string
         */
        private $physicalName = '';

        /**
         * Nielsen Soundscan Digital Sales Login Username
         * @var string
         */
        private $digitalName = '';

        /**
         * Nielsen Soundscan Physical Sales Login Password
         * @var string
         */
        private $physicalPwd = '';

        /**
         * Nielsen Soundscan Digital Sales Login Password
         * @var string
         */
        private $digitalPwd = '';

        /**
         * Nielsen Soundscan Physical Account No
         * @var string
         */
        private $physicalAccount = '';

        /**
         * Nielsen Soundscan Digital Account No
         * @var string
         */
        private $digitalAccount = '';

        /**
         * WooCommerce Category for Music
         * @var string
         */
        private $wcCategory = '';

        /**
         * WooCommerce SubCategory for Tracks (Singles)
         * @var string
         */
        private $trackCategory = '';

        /**
         * WooCommerce SubCategory for Albums
         */
        private $albumCategory = '';

        /**
         * WooCommerce Attribute for EAN
         * @var string
         */
        private $eanAttribute = '';

        /**
         * WooCommerce Attribute for UPC
         * @var string
         */
        private $upcAttribute = '';

        /**
         * WooCommerce Attribute for ISRC
         * @var string
         */
        private $isrcAttribute = '';

        /**
         * Minimum Price for a Qualifying Digital Track
         * @var float
         */
        private $digitalMinTrackPrice = 0.39;

        /**
         * Minimum Price for a Qualifying Digital Track
         * @var float
         */
        private $digitalMinAlbumPrice = 3.49;

        /**
         * Minimum Price for a Qualifying Physical Track
         * @var float
         */
        private $physicalMinTrackPrice = 4.99;

        /**
         * Minimum Price for a Qualifying Physical Album
         * @var float
         */
        private $physicalMinAlbumPrice = 4.99;

        public function __construct()
        {
            $this->id = 'wc-soundscan-settings';
            $this->method_title = __('Soundscan', 'woocommerce-soundscan');
            $this->method_description = __(
                'Nielsen Soundscan FTP Upload Settings',
                'woocommerce-soundscan'
            );

            $this->initFormFields();
            $this->init_settings();

            $this->ftpHost = $this->get_option(self::FTP_HOST, '');
            $this->chainNo = $this->get_option(self::CHAIN_NO, '');
            $this->physicalName = $this->get_option(self::LOGIN_PHYSICAL_NAME, '');
            $this->digitalName = $this->get_option(self::LOGIN_DIGITAL_NAME, '');
            $this->physicalPwd = $this->get_option(self::LOGIN_PHYSICAL_PWD, '');
            $this->digitalPwd = $this->get_option(self::LOGIN_DIGITAL_PWD, '');
            $this->physicalAccount = $this->get_option(self::ACCOUNT_NO_PHYSICAL, '');
            $this->digitalAccount = $this->get_option(self::ACCOUNT_NO_DIGITAL, '');
            $this->wcCategory = $this->get_option(self::MUSIC_CATEGORY, '');
            $this->trackCategory = $this->get_option(self::TRACK_CATEGORY, '');
            $this->albumCategory = $this->get_option(self::ALBUM_CATEGORY, '');
            $this->isrcAttribute = $this->get_option(self::ISRC_ATTRIBUTE, '');
            $this->eanAttribute = $this->get_option(self::EAN_ATTRIBUTE, '');
            $this->upcAttribute = $this->get_option(self::UPC_ATTRIBUTE, '');

            add_action(
                'woocommerce_update_options_integration_' . $this->id,
                [$this, 'process_admin_options']
            );
            add_filter(
                'woocommerce_settings_api_sanitized_fields_' . $this->id,
                [$this, 'sanitizeOptions']
            );
        }

        /**
         * Initialize Woocommerce Soundscan Settings
         * @return void
         */
        public function initFormFields()
        {
            $this->form_fields = [
                'ftpHost'           =>  [
                    'title'             => __(
                        '(S)FTP Host',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'text',
                    'description'       => __(
                        'The Nielsen (S)FTP address, beginning with ftp:// or ftps://.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                    'placeholder'       =>  'ftps://'
                ],
                'chainNo'           =>  [
                    'title'             => __(
                        'Chain Number',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'text',
                    'description'       => __(
                        'Your assigned chain number.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                    'placeholder'       =>  '40xx'
                ],
                'physicalAccount'   =>  [
                    'title'             => __(
                        'Physical Sales Account Number',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'text',
                    'description'       => __(
                        'Your Nielsen Soundscan account number for physical sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'physicalName'      =>  [
                    'title'             => __(
                        'Physical Sales FTP Username',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'text',
                    'description'       => __(
                        'Your FTP login username for physical sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'physicalPwd'       =>  [
                    'title'             => __(
                        'Physical Sales FTP Password',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'password',
                    'description'       => __(
                        'Your FTP login password for physical sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'digitalAccount'    =>  [
                    'title'             => __(
                        'Digital Sales Account Number',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'text',
                    'description'       => __(
                        'Your Nielsen Soundscan account number for digital sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'digitalName'       =>  [
                    'title'             => __(
                        'Digital Sales FTP Username',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'text',
                    'description'       => __(
                        'Your FTP login username for digital sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'digitalPwd'        =>  [
                    'title'             => __(
                        'Digital Sales FTP Password',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'password',
                    'description'       => __(
                        'Your FTP login password for digital sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'wcCategory'            =>  [
                    'title'             => __(
                        'Music Product Category',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'music',
                    'description'       => __(
                        'The WooCommerce product category for music. Required for all physical and digital sales reporting.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'trackCategory'         =>  [
                    'title'             => __(
                        'Product Track (Single) Subcategory',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'track',
                    'description'       => __(
                        'The WooCommerce product subcategory for music tracks (singles). Required for digital sales reporting.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'albumCategory'         =>  [
                    'title'             => __(
                        'Product Album Subcategory',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'album',
                    'description'       => __(
                        'The WooCommerce product category for music albums. Required for digital sales reporting.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'eanAttribute'          =>  [
                    'title'             => __(
                        'WooCommerce EAN Attribute',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'text',
                    'description'       => __(
                        'A WooCommerce attribute should exist on the product for either the EAN or UPC. This is required for both digital and physical sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'upcAttribute'          =>  [
                    'title'             => __(
                        'WooCommerce UPC Attribute',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'test',
                    'description'       => __(
                        'A WooCommerce attribute should exist on the product for either the EAN or UPC. This is required for both digital and physical sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'isrcAttribute'         =>  [
                    'title'             => __(
                        'WooCommerce ISRC Attribute',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'test',
                    'description'       => __(
                        'A WooCommerce attribute should exist on the product for either the EAN or UPC. This is required for digital sales.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          => true,
                ],
                'digitalTrackMinPrice'  =>  [
                    'title'             => __(
                        'Digital Track (Single) Minimum Price',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'number',
                    'description'       => __(
                        'To qualify for Soundscan Reporting the sale must be for a mimimum amount. Up to date figures can be obtained from Nielsen.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          =>  true,
                    'default'           =>  '0.39',
                    'custom_attributes' =>  [
                        'step'          =>  '0.01',
                        'min'           =>  0,
                        'max'           =>  '99.99'
                    ]
                ],
                'physicalTrackMinPrice' =>  [
                    'title'             => __(
                        'Physical Track (Single) Minimum Price',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'number',
                    'description'       => __(
                        'To qualify for Soundscan Reporting the sale must be for a mimimum amount. Up to date figures can be obtained from Nielsen.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          =>  true,
                    'default'           =>  '4.99',
                    'custom_attributes' =>  [
                        'step'          =>  '0.01',
                        'min'           =>  0,
                        'max'           =>  '99.99'
                    ]
                ],
                'digitalAlbumMinPrice'  =>  [
                    'title'             => __(
                        'Digital Album Minimum Price',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'number',
                    'description'       => __(
                        'To qualify for Soundscan Reporting the sale must be for a mimimum amount. Up to date figures can be obtained from Nielsen.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          =>  true,
                    'default'           =>  '3.49',
                    'custom_attributes' =>  [
                        'step'          =>  '0.01',
                        'min'           =>  0,
                        'max'           =>  '99.99'
                    ]
                ],
                'physicalAlbumMinPrice' =>  [
                    'title'             => __(
                        'Physical Album Minimum Price',
                        'woocommerce-soundscan'
                    ),
                    'type'              => 'number',
                    'description'       => __(
                        'To qualify for Soundscan Reporting the sale must be for a mimimum amount. Up to date figures can be obtained from Nielsen.',
                        'woocommerce-soundscan'
                    ),
                    'desc_tip'          =>  true,
                    'default'           =>  '4.99',
                    'custom_attributes' =>  [
                        'step'          =>  '0.01',
                        'min'           =>  0,
                        'max'           =>  '99.99'
                    ]
                ]
            ];
        }

        /**
         * Generate the Field HTML for Listing the WC Categories for Tracks
         * @param string    $key       WC Field Key
         * @param mixed[]   $data      WC Field Data Attributes
         * @return string              WC Integration HTML for Category Field
         */
        public function generate_track_html(string $key, array $data): string
        {
            return $this->generateMusicCategoriesHTML(
                $key,
                $data,
                self::TRACK_CATEGORY
            );
        }

        /**
         * Generate the Field HTML for Listing the WC Categories for Albums
         * @param string    $key       WC Field Key
         * @param mixed[]   $data      WC Field Data Attributes
         * @return string              WC Integration HTML for Category Field
         */
        public function generate_album_html(string $key, array $data): string
        {
            return $this->generateMusicCategoriesHTML(
                $key,
                $data,
                self::ALBUM_CATEGORY
            );
        }

        /**
         * Generate the Field HTML for Listing the WC Categories for Music
         * @param string    $key       WC Field Key
         * @param mixed[]   $data      WC Field Data Attributes
         * @return string              WC Integration HTML for Category Field
         */
        public function generate_music_html(string $key, array $data): string
        {
            return $this->generateMusicCategoriesHTML(
                $key,
                $data,
                self::MUSIC_CATEGORY
            );
        }

        /**
         * Generate the Field HTML for Listing the WC Categories
         * @param string    $key       WC Field Key
         * @param mixed[]   $data      WC Field Data Attributes
         * @param string    $option    WC Soundscan Option Name
         * @return string              WC Integration HTML for Category Field
         */
        public function generateMusicCategoriesHTML(
            string $key,
            array $data,
            string $option
        ): string {
            $field = $this->plugin_id . $this->id . '_' . $key;
            $defaults = [
                'class'             => 'wss-settings-select',
                'css'               => '',
                'custom_attributes' => [],
                'desc_tip'          => false,
                'description'       => '',
                'title'             => '',
            ];
            $data = wp_parse_args($data, $defaults);
            $args = [
                'taxonomy'   => 'product_cat',
            ];
            $categories = get_terms($args);

            ob_start();
            $html = ob_get_clean();
            ?>
            <table class="form-table">
                <tbody>
                    <tr valign="top">
                        <th scope="row" class="titledesc">
                            <label for="<?php echo esc_attr($field); ?>">
                                <?php echo wp_kses_post($data['title']); ?>
                            </label>
                            <?php echo $this->get_tooltip_html($data); ?>
                        </th>
                        <td class="forminp">
                            <fieldset>
                                <legend class="screen-reader-text">
                                    <span>
                                        <?php echo wp_kses_post($data['title']); ?>
                                    </span>
                                </legend>
                                <select class="<?php echo esc_attr($data['class']); ?>" name="<?php echo esc_attr($field); ?>" style="<?php echo esc_attr($data['css']); ?>" <?php echo $this->get_custom_attribute_html($data); ?>>
                                    <option value=""></option>
                                    <?php foreach ($categories as $cat) : ?>
                                        <option <?php selected($cat->name, $this->get_option($option)); ?> value="<?php echo esc_attr($cat->name); ?>">
                                            <?php printf(esc_html__('%s', 'woocommerce-soundscan'), $cat->name); ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                                <?php echo $this->get_description_html($data); ?>
                            </fieldset>
                        </td>
                    </tr>
                </tbody>
            </table>
            <?php

            return $html;
        }

        /**
         * Sanitize Woocommerce Soundscan Settings
         * @param mixed[] $settings     Dirty Settings
         * @return mixed[]              Clean Settings
         */
        public function sanitizeOptions(array $settings = []): array
        {
            $cleanSettings = [];

            if (isset($settings[self::FTP_HOST])) {
                $cleanSettings[self::FTP_HOST] = esc_url_raw(
                    $settings[self::FTP_HOST],
                    ['ftp', 'ftps']
                );
            }

            if (isset($settings[self::CHAIN_NO])) {
                $chainNo = trim($settings[self::CHAIN_NO]);
                $cleanSettings[self::CHAIN_NO] = sanitize_text_field(
                    $chainNo
                );
            }

            if (isset($settings[self::LOGIN_PHYSICAL_NAME])) {
                $cleanSettings[self::LOGIN_PHYSICAL_NAME] = sanitize_text_field(
                    $settings[self::LOGIN_PHYSICAL_NAME]
                );
            }

            if (isset($settings[self::LOGIN_DIGITAL_NAME])) {
                $cleanSettings[self::LOGIN_DIGITAL_NAME] = sanitize_text_field(
                    $settings[self::LOGIN_DIGITAL_NAME]
                );
            }

            if (isset($settings[self::LOGIN_PHYSICAL_PWD])) {
                $cleanSettings[self::LOGIN_PHYSICAL_PWD] = $settings[self::LOGIN_PHYSICAL_PWD];
            }

            if (isset($settings[self::LOGIN_DIGITAL_PWD])) {
                $cleanSettings[self::LOGIN_DIGITAL_PWD] = $settings[self::LOGIN_DIGITAL_PWD];
            }

            if (isset($settings[self::ACCOUNT_NO_PHYSICAL])) {
                $cleanSettings[self::ACCOUNT_NO_PHYSICAL] = sanitize_text_field(
                    $settings[self::ACCOUNT_NO_PHYSICAL]
                );
            }

            if (isset($settings[self::ACCOUNT_NO_DIGITAL])) {
                $cleanSettings[self::ACCOUNT_NO_DIGITAL] = sanitize_text_field(
                    $settings[self::ACCOUNT_NO_DIGITAL]
                );
            }

            if (isset($settings[self::EAN_ATTRIBUTE])) {
                $cleanSettings[self::EAN_ATTRIBUTE] = sanitize_text_field(
                    $settings[self::EAN_ATTRIBUTE]
                );
            }

            if (isset($settings[self::UPC_ATTRIBUTE])) {
                $cleanSettings[self::UPC_ATTRIBUTE] = sanitize_text_field(
                    $settings[self::UPC_ATTRIBUTE]
                );
            }

            if (isset($settings[self::ISRC_ATTRIBUTE])) {
                $cleanSettings[self::ISRC_ATTRIBUTE] = sanitize_text_field(
                    $settings[self::ISRC_ATTRIBUTE]
                );
            }

            if (isset($settings[self::MUSIC_CATEGORY])) {
                $cleanSettings[self::MUSIC_CATEGORY] = sanitize_text_field(
                    $settings[self::MUSIC_CATEGORY]
                );
            }

            if (isset($settings[self::TRACK_CATEGORY])) {
                $cleanSettings[self::TRACK_CATEGORY] = sanitize_text_field(
                    $settings[self::TRACK_CATEGORY]
                );
            }

            if (isset($settings[self::ALBUM_CATEGORY])) {
                $cleanSettings[self::ALBUM_CATEGORY] = sanitize_text_field(
                    $settings[self::ALBUM_CATEGORY]
                );
            }

            if (isset($settings[self::DIGITAL_TRACK_MIN_PRICE])) {
                $cleanSettings[self::DIGITAL_TRACK_MIN_PRICE] = round(filter_var(
                    $settings[self::DIGITAL_TRACK_MIN_PRICE],
                    FILTER_SANITIZE_NUMBER_FLOAT,
                    FILTER_FLAG_ALLOW_FRACTION
                ), 2);
            }

            if (isset($settings[self::PHYSICAL_TRACK_MIN_PRICE])) {
                $cleanSettings[self::PHYSICAL_TRACK_MIN_PRICE] = round(filter_var(
                    $settings[self::PHYSICAL_TRACK_MIN_PRICE],
                    FILTER_SANITIZE_NUMBER_FLOAT,
                    FILTER_FLAG_ALLOW_FRACTION
                ), 2);
            }

            if (isset($settings[self::DIGITAL_ALBUM_MIN_PRICE])) {
                $cleanSettings[self::DIGITAL_ALBUM_MIN_PRICE] = round(filter_var(
                    $settings[self::DIGITAL_ALBUM_MIN_PRICE],
                    FILTER_SANITIZE_NUMBER_FLOAT,
                    FILTER_FLAG_ALLOW_FRACTION
                ), 2);
            }

            if (isset($settings[self::PHYSICAL_ALBUM_MIN_PRICE])) {
                $cleanSettings[self::PHYSICAL_ALBUM_MIN_PRICE] = round(filter_var(
                    $settings[self::PHYSICAL_ALBUM_MIN_PRICE],
                    FILTER_SANITIZE_NUMBER_FLOAT,
                    FILTER_FLAG_ALLOW_FRACTION
                ), 2);
            }

            return $cleanSettings;
        }

        /**
         * Validate FTP Host Field
         * @param string $key               FTP Host Option Setting Field
         * @param string $value             FTP Host Value
         * @return string                   FTP Host Value
         */
        public function validate_ftpHost_field(string $key, string $value = ''): string
        {
            if (!empty($value) && preg_match('/^ftps?:\/\//', $value) !== 1) {
                \WC_Admin_Settings::add_error(
                    __(
                        'The FTP Host must start with ftps:// or ftp://',
                        'woocommerce-soundscan'
                    )
                );
            }

            return $value;
        }

        /**
         * Validate Chain Number Field
         * @param string $key               Chain No Option Setting Field
         * @param string $value             Chain No Value
         * @return string                   Chain No Value
         */
        public function validate_chainNo_field(string $key, string $value = ''): string
        {
            if (!empty($value) && (substr($value, 0, 2) !== '40' ||
                mb_strlen($value, 'utf-8') !== 4)) {
                \WC_Admin_Settings::add_error(
                    __(
                        'Your chain number should be 4 characters long and begin with 40.',
                        'woocommerce-soundscan'
                    )
                );
            }

            return $value;
        }

        /**
         * Validate Physical Account Number Field
         * @param string $key           Physical Account No Option Setting Field
         * @param string $value         Physical Account No Value
         * @return string               Physical Account No Value
         */
        public function validate_physicalAccount_field(string $key, string $value = ''): string
        {
            if (!empty($value) && mb_strlen($value, 'utf-8') !== 5) {
                \WC_Admin_Settings::add_error(
                    __(
                        'Your physical account number should be 5 characters long.',
                        'woocommerce-soundscan'
                    )
                );
            }

            return $value;
        }

        /**
         * Validate Digital Account Number Field
         * @param string $key           Digital Account No Option Setting Field
         * @param string $value         Digital Account No Value
         * @return string               Digital Account No Value
         */
        public function validate_digitalAccount_field(string $key, string $value = ''): string
        {
            if (!empty($value) && mb_strlen($value, 'utf-8') !== 5) {
                \WC_Admin_Settings::add_error(
                    __(
                        'Your digital account number should be 5 characters long.',
                        'woocommerce-soundscan'
                    )
                );
            }

            return $value;
        }
    }
} else {
    throw new \Exception('Woocommerce Soundscan Settings class exists');
}
